package com.ramon.mobileappws.service.impl;

import com.ramon.mobileappws.io.entity.UserEntity;
import com.ramon.mobileappws.io.repository.UserRepository;
import com.ramon.mobileappws.service.UserService;
import com.ramon.mobileappws.shared.Utils;
import com.ramon.mobileappws.shared.dto.UserDto;
import org.springframework.beans.BeanUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Service;

@Service
public class UserServiceImpl implements UserService {

    private final UserRepository userRepository;
    private final Utils utils;
    private final BCryptPasswordEncoder bCryptPasswordEncoder;

    @Autowired
    public UserServiceImpl(UserRepository userRepository, Utils utils, BCryptPasswordEncoder bCryptPasswordEncoder) {
        this.userRepository = userRepository;
        this.utils = utils;
        this.bCryptPasswordEncoder = bCryptPasswordEncoder;
    }

    @Override
    public UserDto createUser(UserDto userDto) {
        // Checks if Email already used
        if (userRepository.findByEmail(userDto.getEmail()) != null) throw new RuntimeException("Email already in use.");
        // basic properties being mapped to user entity
        UserEntity userEntity = new UserEntity();

        BeanUtils.copyProperties(userDto, userEntity);

        //set public userId generated by Utils class, set encrypted password with the help of BCryptPasswordEncoder
        String publicUserId = utils.generateUserId(30);
        String encryptedPassword = bCryptPasswordEncoder.encode(userDto.getPassword());
        userEntity.setUserId(publicUserId);
        userEntity.setEncryptedPassword(encryptedPassword);


        // Storing user in db with updated properties and returning a dto with new properties
        // to be passed onto controller
        UserEntity storedUserDetails = userRepository.save(userEntity);

        UserDto returnValue = new UserDto();
        BeanUtils.copyProperties(storedUserDetails, returnValue);

        return returnValue;
    }

    // Method below comes from spring security

    @Override
    public UserDetails loadUserByUsername(String s) throws UsernameNotFoundException {
        return null;
    }
}
